
name = "andaman-travel-website"
compatibility_date = "2025-04-08"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

[[d1_databases]]
binding = "DB"
database_name = "random_id"
database_id = "10183848-4cc7-4198-b8c7-1374015ab09c"

[build]
command = "npm run build"
publish = ".next" 



pages_build_output_dir = ".vercel/output/static"
