#:schema node_modules/wrangler/config-schema.json
name = "reachandaman" # You can keep this, but Pages primarily uses the project name set in the UI
compatibility_date = "2024-09-23" # Keep this or update to a recent date
compatibility_flags = ["nodejs_compat"] # Keep this

# --- Bindings Section ---
[[d1_databases]]
binding = "DB" # Ensure this matches your code (e.g., env.DB)
database_name = "random_id" # Ensure this matches your D1 database name in Cloudflare
database_id = "10183848-4cc7-4198-b8c7-1374015ab09c" # Ensure this is correct

# --- Environment Variables ---
[vars]
# Add your environment variables here
# Example: API_KEY = "your-api-key"
# These will be available in your application as env.API_KEY

# --- Build Configuration ---
[build]
command = "npm run build"

# --- Cloudflare Pages specific settings ---
[site]
bucket = ".next/standalone"
